# Generated by Django 4.0.5 on 2022-11-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_content', models.TextField(max_length=1000)),
                ('com_date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentVotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_com_date_created', models.DateTimeField(auto_now_add=True)),
                ('vote_com_rating', models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PostsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=80)),
                ('post_slug', models.SlugField(blank=True, max_length=80, null=True)),
                ('post_picture', models.ImageField(blank=True, upload_to='')),
                ('post_content', models.TextField(max_length=1000)),
                ('post_date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ViewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_user', models.CharField(max_length=80)),
                ('view_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_post', to='Blog_App.postsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PostVotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_post_date_created', models.DateTimeField(auto_now_add=True)),
                ('vote_post_rating', models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], max_length=10)),
                ('vote_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_post', to='Blog_App.postsmodel')),
            ],
        ),
    ]
