# Generated by Django 4.0.5 on 2022-11-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_App', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='post_tag',
            field=models.ManyToManyField(blank=True, related_name='post_tag', to='Blog_App.tagsmodel'),
        ),
    ]
